### ISSUE TITLE
"MIX_TARGET=rpi3 mix" should give a nicer error message

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#101]
Currently, you get a wall of error messages from the system trying to load cross-compiled binaries. It seems like this should be intercepted to error out with something like:

"Cannot run build intended for rpi3 on the host. Try running 'mix compile' or 'mix firmware'"

Or something similar. It seems like something that people will accidentally type before they come to appreciate the cross-compiled nature of Nerves. Or, if they're like me, and are running on Linux with binfmt magic automatically redirecting foreign architecture binaries to qemu, they'll get something even more surprising.

**Comment by mobileoverlord** [comment]
This has been fixed in nerves_bootstrap. In the next version it will warn, but it will currently raise.
