### ISSUE TITLE
NERVES_SYSTEM isn't documented

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#130]
I noticed that neither `NERVES_SYSTEM` nor `NERVES_TOOLCHAIN` were documented or maybe I couldn't find it? This is the main way that I use Nerves, so I was wondering if these should be documented.

**Comment by electricshaman** [comment]
I would vote no until we fix the weird discrepancies between NERVES_SYSTEM and the "new way."  You had previously asked me to look into a wrong set/unset message but what I uncovered was a litte more serious than just fixing the message itself

**Comment by GregMefford** [comment]
@electricshaman I'm curious if you think the situation has changed at this point, with the updated docs here: https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system

I still want to spend some time with @fhunleth as well, understanding in more detail how his preferred workflow differs, so we can fix this documentation bug.

**Comment by electricshaman** [comment]
I'll take a look this weekend!

**Comment by electricshaman** [comment]
@GregMefford Looks good!  👍

**Comment by ConnorRigby** [comment]
It seems we have docs for this now, but they aren't included in hexdocs. Is there a reason for this?
