### ISSUE TITLE
Support for Erlang/OTP 20

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves#139]
When building firmware on a host that has Erlang/OTP 20 installed, the following error message appears:

```
** (Mix) Major version mismatch between host and target Erlang/OTP versions
  Host version: 20
  Target version: 19
This will likely cause Erlang code compiled for the target to fail in
unexpected ways. Install an Erlang OTP release that matches the target
version before continuing.
```

This is because Nerves requires that your host OTP version (running on the machine that's building the firmware) match the version that will run on the target (embedded system). Since the currently-released versions of the supported Nerves Systems are using OTP 19, you need to use OTP 19 to build your firmware.

We plan to support OTP 20 in upcoming releases of the supported Systems, but the constraint of matching your host OTP version will continue to exist for the foreseeable future. So at that point, OTP 19 will no longer be supported on the host for System versions beyond that point.

To make this process easier to manage and avoid having to uninstall/reinstall Erlang system-wide, we recommend using a version-management tool like `asdf` to easily switch between versions of your build tools, as described here: http://embedded-elixir.com/post/2017-05-23-using-asdf-vm/.

**Comment by fhunleth** [comment]
OTP 20 is in the [nerves_system_br v0.13.0](https://github.com/nerves-project/nerves_system_br/releases/tag/v0.13.0). It has propagated to most of the officially supported systems now so it should be a matter of upgrading your `nerves_system_*` dep to pull it in. Check your `nerves_system_*` repo for more information if this doesn't work.
