### ISSUE TITLE
Application partition documentation is out of date

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#152]
The current documentation talks about the FAT filesystem for persisting data. It's now EXT4. More information is at https://github.com/nerves-project/nerves_runtime#filesystem-initialization. Some of that could be reused or modified to make it more accessible to a new Nerves user.

**Comment by mobileoverlord** [comment]
Looks like these docs are up to date and discuss how the default application data partition is formatted with ext4

**Comment by mobileoverlord** [comment]
Sorry I was looking at the wrong docs. I reopened this issue.

**Comment by GregMefford** [comment]
Fixed by #159
