### ISSUE TITLE
rootfs_additions -> rootfs_overlay

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#164]
The `rootfs_additions` config variable and directory name need to be updated to `rootfs_overlay` now that we're following the Buildroot naming convention. A `git grep rootfs_additions` looks like it finds everything that needs to change. The only trick is to make sure that the `rootfs_additions` key still works so as to not break existing projects.

**Comment by GregMefford** [comment]
Resolved by #165.
