### ISSUE TITLE
Add a Mix task for packaging a Nerves system artifact

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves#182]
Currently, it's kind of complicated to create a `.tar.gz` file for a custom system that can be uploaded to an HTTP cache location.

I propose that we add a `mix system.artifact` or `mix nerves.system.artifact` task that would build and package the artifact, then tell you the output location where it was placed, so you can upload it.

I think this would live in the `Docker` and `Local` providers (not the `bootstrap` archive), so the `nerves.` prefix on the task shouldn't be necessary unless we want it to be consistent with `mix nerves.system.shell`.

**Comment by mobileoverlord** [comment]
Fixed in v0.9.0
See: 
`mix nerves.artifact`
