### ISSUE TITLE
nerves.system.shell drops you into different paths between Linux and OSX

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#200]
It would be nice to have them be the same or give the illusion of sameness for people who write documentation or do training.

For example:

On OSX, nerves.system.shell drops you into `/nerves/build` and to reach the system from that directory, you reference `../env/system_name/`

On Linux, nerves.system.shell drops you into the `<system directory>/.nerves/artifacts/nerves_system_blablabla/` directory off the system and then to copy back to the system, you have to reference `../../..`

As a side topic, creating build directories outside of the project that runs `mix nerves.system.shell` feels really wrong since it feels like the build directory could be shared with another project. I wasn't ready to create a bug on that, but I wanted to mention my concern in case it influenced how this issue was resolved.

**Comment by mobileoverlord** [comment]
This is an inconsistency, but, this bug is actually a feature that we are using to fix issues with building some lower level packages specifically QtWebEngine which has a file length limit even on linux. Lets revisit this if it becomes a pain
