### ISSUE TITLE
Automatically check for Nerves archive updates

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#202]
It would be really nice if the Nerves archive could automatically check for an update in a similar way as the hex archive does it.

**Comment by GregMefford** [comment]
I think if we do #204, this will will be much easier because the `nerves_bootstrap` archive would be a separately-versioned Hex package that we could potentially install at a particular version instead of only the latest release.

**Comment by mobileoverlord** [comment]
Now that `nerves_bootstrap` is on hex we should be able to make a call to resolve the latest version from the repository periodically and present a message that an update is available.

**Comment by mobileoverlord** [comment]
Fixed in v0.9.0
