### ISSUE TITLE
Update Systems.md for deprecation of nerves.exs

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves#207]
The "new way" to configure Nerves packages is now in their `mix.exs`, not `nerves.exs`.
https://github.com/nerves-project/nerves/pull/176

We should probably document the new convention with an aside about the now-deprecated method that also works for now, or something like that.

Looks like there are also some references in `package.ex` and potentially other places.

**Comment by mobileoverlord** [comment]
@GregMefford let me know if there is anything else we needed to add as per information on this. I took a pass through and merged it in.
