### ISSUE TITLE
Installation instructions reference Erlang version not buildable on OS/X 10.13

### ISSUE THREAD

**Issue by timgilbert** [nerves-project/nerves#228]
Hi! I'm new to ASDF and elixir. When I was trying to follow the installation instructions on MacOS High Sierra, I ran into [this asdf bug](https://github.com/asdf-vm/asdf-erlang/issues/40) which crashes out when running `mix local.hex`. The bug is fixed in erlang 20.1, and I was able to complete the instructions using that version instead of `20.0`.

I'm happy to submit a PR that just updates those versions in `docs/Installation.md`, but as I'm a total newbie I don't know if there will be other downstream effects from the version bump so I thought I'd file an issue first.

**Comment by fhunleth** [comment]
Thanks for letting us know about this. I went ahead and bumped the versions to what I'm using in a PR for the others to review.
