### ISSUE TITLE
File name with full hash longer 143 characters aren't supported by ecryptfs

### ISSUE THREAD

**Issue by webengineer-max** [nerves-project/nerves#250]
Filenames like .nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-0.13.0-D25664C99BC7E3023A2C093C726649E7D50333B9F3887738634F124C9B5BA173.tar.xz.XXXXXX longer than 143 characters aren't supported by ecryptfs (https://bugs.launchpad.net/ecryptfs/+bug/344878). As a result I got error

```
mktemp: failed to create directory via template '/home/profi/Code/tk/deps/rpi3/nerves_system_rpi3/.nerves/artifacts/nerves_system_rpi3-portable-0.20.0/build/.nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-0.13.0-D25664C99BC7E3023A2C093C726649E7D50333B9F3887738634F124C9B5BA173.tar.xz.XXXXXX': File name too long
```

during `mix firmware` inside encrypted home folder.

### Environment
* Erlang version: 20
* Elixir version: 1.6.1
* Operating system: Ubuntu 17.10
* Filesystem: ecryptfs (libecryptfs1/artful,now 111-0ubuntu5 amd64)
* Nerves Environment Info:

|nerves_bootstrap| Environment Package List

  Pkg:      nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:      0.13.1
  Type:     toolchain
  Provider: {Nerves.Artifact.Providers.Local, []}

  Pkg:      nerves_toolchain_ctng
  Vsn:      1.3.1
  Type:     toolchain_platform
  Provider: nil

  Pkg:      nerves_system_rpi3
  Vsn:      0.20.0
  Type:     system
  Provider: {Nerves.Artifact.Providers.Local, []}

  Pkg:      nerves_system_br
  Vsn:      0.17.0
  Type:     system_platform
  Provider: nil

|nerves_bootstrap| Loadpaths Start

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /home/profi/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-0.13.1
  system:     /home/profi/.nerves/artifacts/nerves_system_rpi3-portable-0.20.0
  app:        /home/profi/Code/tk/apps/fw

|nerves_bootstrap| Loadpaths End

### Current behavior

mktemp: failed to create directory via template ‘/home/profi/Code/tk/deps/rpi3/nerves_system_rpi3/.nerves/artifacts/nerves_system_rpi3-portable-0.20.0/build/.nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-0.13.0-D25664C99BC7E3023A2C093C726649E7D50333B9F3887738634F124C9B5BA173.tar.xz.XXXXXX’: File name too long

#### Manual check

$ mktemp .nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-0.13.0-D25664C99BC7E3023A2C093C726649E7D50333B9F3887738634F124C9B5BA173.tar.xz.XXXXXX

#### Console session

https://gist.github.com/webengineer-max/818ee78e19a625056da9fea81a8959fa

### Expected behavior

No error from mktemp.

**Comment by mobileoverlord** [comment]
@webengineer-max Thanks for reporting this. The whole sum isn't necessary and I just put together a fix for this that I hope to have out in `0.11.0` soon.

**Comment by webengineer-max** [comment]
Thank you Justin!

**Comment by mobileoverlord** [comment]
I just pushed 0.11.0 to hex. Can you give that a try and see if it helps?

**Comment by mobileoverlord** [comment]
This has been confirmed working, but, for anyone who is doing a custom system build. The toolchain url will need to be changed in the `nerves_defconfig` to the shor version otherwise you will still be in the same position. These will all be getting truncated to the short version on the next toolchain / system release.
