### ISSUE TITLE
Override $(AR) when crosscompiling

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#297]
Currently we're overriding `$(CC)` and `$(CXX)`.  `clixir` requires `$(AR)` and it seems like Nerves should override that variable as well.

This is a note to verify that `$(AR)` isn't set already and assuming that it's not, to add it to the list in `nerves_system_br` (for Erlang/low level Nerves users) and here in `nerves`.

**Comment by cdegroot** [comment]
(Just in case someone else stumbles here before this gets picked up, below is the work-around to include into your Makefile with thanks to @fhunleth for pointing me in the right direction)

```
ifneq ($(CROSSCOMPILE),)                                                                                              
 AR = $(CROSSCOMPILE)-ar                                                                                               
 endif    
```

Should work for NM, OBJDUMP, .... as well of course in case that these executables give trouble (mostly from compiling from MacOS where the binary utilities are quite incompatible with Linux' expectations).
