### ISSUE TITLE
The documentation for UI is not complete

### ISSUE THREAD

**Issue by ulve** [nerves-project/nerves#32]
The documentation for how to crete a UI is somewhat out of date. At the moment sqlite does not work and is not needed neither is brunch. Configuration for the ui app in the fw app is missing and also configuration for the OTP application is missing. fw.ex must also have a child worker that sets up networking.

I have created a pr that fixes this #31

**Comment by mobileoverlord** [comment]
merged
https://github.com/nerves-project/nerves/commit/934b5d15199339add002e34aa452a93e668f1001
