### ISSUE TITLE
Document ssh-askpass dependency on Linux

### ISSUE THREAD

**Issue by bendiken** [nerves-project/nerves#33]
On @DanKomorny's fresh Lubuntu 16.04 installation:

    $ NERVES_TARGET=rpi mix firmware.burn
    Use 7.4 GiB memory card found at /dev/sdb? [Yn] y
    sudo: unable to run /usr/bin/ssh-askpass: No such file or directory

The relevant bit of code is at: [`lib/mix/tasks/firmware.burn.ex`](https://github.com/nerves-project/nerves/blob/d8e6bc217bde030813c88d4ea05b0782903c069b/lib/mix/tasks/firmware.burn.ex#L47)

Resolved by `sudo apt-get install ssh-askpass`.

The Nerves [installation guide](https://hexdocs.pm/nerves/installation.html) should probably document this requirement on Linux?

**Comment by mobileoverlord** [comment]
Sounds good. I think that this host requirement should be in the docs. Do you want me to add it or can you make a separate PR for this? :)

Thanks!

**Comment by bendiken** [comment]
Sure thing, I'll send a pull request in a bit.

**Comment by GregMefford** [comment]
@bendiken: I went ahead and fixed it. Thanks for pointing out the missing step! :balloon:

**Comment by bendiken** [comment]
Thanks, @GregMefford! However, note that the [getting started guide](https://hexdocs.pm/nerves/getting-started.html) never mentions `sudo`, so the text you added is perhaps somewhat misleading as-is given that we aren't actually ever asking people to use `sudo mix firmware.burn`.

**Comment by GregMefford** [comment]
@bendiken: good point. Maybe it's simpler and more consistent to just say it's required. I've personally never noticed that it's missing because I just do `sudo mix firmware.burn` :grinning:

**Comment by GregMefford** [comment]
Updated!

**Comment by bendiken** [comment]
Looks good 👍

**Comment by craigbrett17** [comment]
Helped me with a completely unrelated TeamCity SSH issue that was a pain to Google, I didn't know it was an apt package. Thanks!

**Comment by drannex42** [comment]
I know this is several years old, but for anyone else who may end up googling for a solution to `sudo: unable to run /usr/bin/ssh-askpass: No such file or directory`

You need to create a symbolic link between ssh-askpass and your existing askpass installation.
```
ln -s $SSH_ASKPASS /usr/bin/ssh-askpass

# or 

ln -s /location/to/askpass /usr/bin/ssh-askpass

```

If the above didn't work, check to see if you have $SSH_ASKPASS set by running `echo $SSH_ASKPASS` in your terminal. 

If you don't, then you need to either install ssh-askpass (ubuntu is already listed in the docs), or if you are using Fedora, install the gnome askpass with `sudo dnf install gnome-ssh-askpass` and rerun the above.
