### ISSUE TITLE
mix firmware really slow on OSX 

### ISSUE THREAD

**Issue by epinault** [nerves-project/nerves#361]
### Environment

* Elixir version (`elixir -v`):

Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Nerves environment: (`mix nerves.env --info`)

mix nerves.env --info
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start

nerves 1.3.2
  nerves_firmware_ssh 0.3.3
  nerves_init_gadget 0.5.2
  nerves_network 0.3.7
  nerves_network_interface 0.4.4
  nerves_runtime 0.8.0
  nerves_system_br 1.4.5
  nerves_time 0.2.0
  nerves_toolchain_arm_unknown_linux_gnueabihf 1.1.0
  nerves_toolchain_ctng 1.5.0
  nerves_wpa_supplicant 0.3.3

Nerves environment
  MIX_TARGET:   unset
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        /Users/epinault/src/home_kiosk/dashboard_nerves

|nerves_bootstrap| Loadpaths End

* Additional information about your host, target hardware or environment that
  may help

### Current behavior

Trying to build the firmware when using the kiosk is too slow to even build one firmware within 30 min..

% MIX_TARGET=rpi3 mix firmware
==> nerves_system_br
Generated nerves_system_br app
==> kiosk_system_rpi3
Generated kiosk_system_rpi3 app
==> dashboard_nerves

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

Compiling 2 files (.ex)
warning: this clause cannot match because a previous clause at line 34 always matches
  lib/dashboard_nerves/application.ex:36

Generated dashboard_nerves app
|nerves_bootstrap| Building OTP Release...

Updating base firmware image with Erlang release...
Copying rootfs_overlay: /Users/epinault/src/home_kiosk/dashboard_nerves/rootfs_overlay

### Expected behavior

runs fast? the issue is that a lot of the script are using sed and pipe and that does not go very well with Bash on OSX it seems...

**Comment by axelson** [comment]
@epinault 👋  So, are you getting this issue on your new work laptop as well? Also IIRC, you had some sort of additional filesystem installed (although not being used for firmware building), was that FUSE?

**Comment by epinault** [comment]
Yes we are getting that issue. Not FUSE related. It is an issue with OSX and sed. Seems like sed -e | sed -e is slow on OSX. Best way is to combine sed -e together in one command and that fix the problem heavily

**Comment by epinault** [comment]
I believe the issue is that the patch is in but they need to regenerate the actual bundle that contains the script. I think @mobileoverlord was looking into it. Specifically for the kiok_system_rpi3

**Comment by fhunleth** [comment]
Closing since the fix is in the official systems. The issue for the kiosk_system_rpi3 is at https://github.com/LeToteTeam/kiosk_system_rpi3/issues/38.

**Comment by epinault** [comment]
thanks!
