### ISSUE TITLE
to stderr

### ISSUE THREAD

**Issue by henrik-jensen** [nerves-project/nerves#375]
### Environment

* Elixir version (`elixir -v`):
* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that
  may help

### Current behavior

Include errors, stacktraces, screenshots or code that may help us reproduce the
issue.

**Comment by GregMefford** [comment]
Was this submitted without finishing the details? It's not clear from the title what it's about.

**Comment by henrik-jensen** [comment]
Oh I'm sorry. That was an error.
I was reading issue #347 and then closing the tab .
I think I "pocket dialed" it (ctrl+T and some unfortunate github shortcuts) but I didn't notice I actually created an issue. Sorry again, closing it now.
