### ISSUE TITLE
mix nerves.new inside umbrellas do not generate umbrella options

### ISSUE THREAD

**Issue by josevalim** [nerves-project/nerves#38]
Since Elixir v1.2, Elixir generates the following configuration for apps inside umbrellas:

```elixir
     build_path: "../../_build",
     config_path: "../../config/config.exs",
     deps_path: "../../deps",
     lockfile: "../../mix.lock",
```

While nerves generates:

```elixir
    deps_path: "deps/#{@target}",
    build_path: "_build/#{@target}",
```

It is understandable that Nerves does not want to share the deps and build paths with the umbrella due to target configurations (and that's fine IMO) but I would recommend sharing the config and lockfile paths to avoid configuration and dependency conflicts respectivelly.

As an example, here is how the check is implemented in Phoenix:

  * https://github.com/phoenixframework/phoenix/blob/master/installer/lib/phoenix_new.ex#L484-L495
  * https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/mix.exs#L6-L10

**Comment by mobileoverlord** [comment]
fixed in 
nerves-project/nerves@683dee9cf5a16267fb069954a5dc759b106076c8
nerves-project/nerves@773d944ac477578a55642e2c2ca956a8c8b71509
