### ISSUE TITLE
nerves: follow XDG base dir specification

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#386]
Nerves stores global data to `~/.nerves`. The [XDG Base Dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) provides a standard location for these kinds of files. There's an Elixir issue and discussion that have some compelling reasons behind changing. It seems like Nerves should change as well. See:

* https://github.com/elixir-lang/elixir/issues/8818
* https://groups.google.com/forum/#!topic/elixir-lang-core/7nyDfkgRsI0

**Comment by mobileoverlord** [comment]
Starting in Nerves [1.5.2](https://github.com/nerves-project/nerves/releases/tag/v1.5.2) 
 the data directory for Nerves will use `XDG_DATA_HOME` if set. We will revisit supporting the XDG spec more closely in a major version upgrade.
