### ISSUE TITLE
Add warning message when `:releases` is improperly set

### ISSUE THREAD

**Issue by elcritch** [nerves-project/nerves#446]
### Environment

* Elixir version (`elixir -v`): 

> Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
> Elixir 1.9.1 (compiled with Erlang/OTP 22)
> 

* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that
  may help

> |nerves_bootstrap| Environment Package List
> 
>   Pkg:         nerves_toolchain_aarch64_unknown_linux_gnu
>   Vsn:         1.2.0
>   Type:        toolchain
>   BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
> 
>   Pkg:         nerves_toolchain_ctng
>   Vsn:         1.6.0
>   Type:        toolchain_platform
>   BuildRunner: {nil, []}
> 
>   Pkg:         nerves_system_br
>   Vsn:         1.8.5
>   Type:        system_platform
>   BuildRunner: {nil, []}
> 
>   Pkg:         nerves_system_nanopi_core2
>   Vsn:         0.3.0
>   Type:        system
>   BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
> 
> |nerves_bootstrap| Loadpaths Start
> 
> 
> Nerves environment
>   MIX_TARGET:   nanopi_core2
>   MIX_ENV:      dev
> 
> |nerves_bootstrap| Environment Variable List
>   target:     nanopi_core2
>   toolchain:  /home/elcritch/.nerves/artifacts/nerves_toolchain_aarch64_unknown_linux_gnu-linux_x86_64-1.2.0
>   system:     /home/elcritch/.nerves/artifacts/nerves_system_nanopi_core2-portable-0.3.0
>   app:        /home/elcritch/projects/pt/tro_firmware/sensor_router
> 
> |nerves_bootstrap| Loadpaths End
> 

### Current behavior

Upgrading to Nerves 1.6 and Elixir 1.9. Project builds with `mix firmware` but errors out at the end. Looking into the issue the release is being compiled as `_build/nanopi_core2_prod/rel/nil`. 

Tracked it down and turns out it was that I copied the `releases: [{@app, release()}], ` line but missed adding the `@app :name` definition. Setting this properly fixed the issue, but it was tricky to track down and understand what I'd missed.

**Comment by fhunleth** [comment]
This is an old issue. I'm guessing that it probably exists, but I'm not sure what we can do.
