### ISSUE TITLE
'mix firmware.burn --device myimage' creates a file as root

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves#48]
When creating image files, `mix firmware.burn` still wants root permissions on Linux. It shouldn't need those.

Another thought is to add `mix firmware.image <filename>` to create a raw image file.

**Comment by mobileoverlord** [comment]
fixed in master
https://github.com/nerves-project/nerves/commit/6a00923792a3178d3a56cdd84de11ecd6a77285b
