### ISSUE TITLE
fwup".exe" is required even in the Docker environment on Windows

### ISSUE THREAD

**Issue by takasehideki** [nerves-project/nerves#568]
_NOTE: This issue was appeared when we use Docker Desktop for Windows as the development environment.
I understand this issue is too unique. But don't worry, I have already found an idea to fix it._

### Environment

* Elixir version (`elixir -v`):
```
$ elixir -v 
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

* Nerves environment: (`mix nerves.env --info`)
```
$ mix nerves.env --info 
==> nerves
==> hello_nerves
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.13.5
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi3
  Vsn:         1.13.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /root/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.3.2
  system:     /root/.nerves/artifacts/nerves_system_rpi3-portable-1.13.2
  app:        /workspaces/nerves-devcontainer/hello_nerves

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

- Docker Desktop for Windows as development environment (please also see [my post on Elixir Forum](https://elixirforum.com/t/nerves-development-environment-with-docker-and-vs-code/35973)
- WSL 2 Linux kernel was installed

### Current behavior

```
$ ls -l /usr/bin/fwup*
-rwxr-xr-x 1 root root 703000 Oct 31 16:24 /usr/bin/fwup
lrwxrwxrwx 1 root root      4 Nov 26 07:18 /usr/bin/fwup.exe -> fwup
$ rm /usr/bin/fwup.exe 
$ mix firmware 
==> nerves
==> hello_nerves

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

** (Mix) fwup.exe is required by the Nerves tooling.

Please see https://hexdocs.pm/nerves/installation.html for installation
instructions.
```

### Expected behavior

The firmware build succeeds without fwup**.exe**.

### Why it happens

The current implementation checks whether the environment is WSL 2 by the kernel name (`/proc/sys/kernel/osrelease`). 

https://github.com/nerves-project/nerves/blob/5bd888800c97c126476b3ef8059b3dbf9c69d45d/lib/nerves/utils/wsl.ex#L22-L34

If it was true, `fwup.exe` is adopted as the name of fwup.

https://github.com/nerves-project/nerves/blob/5bd888800c97c126476b3ef8059b3dbf9c69d45d/lib/mix/nerves/preflight.ex#L24-L34

The reason why this issue appeared is the Docker Desktop for Windows uses WSL 2 kernel as the back-end. So this environment also has "microsoft".

```
iex(1)> System.cmd("cat", ["/proc/sys/kernel/osrelease"]) 
{"4.19.128-microsoft-standard\n", 0}
```

The simplest way to avoid this issue is to create the symbolic link of `fwup.exe` to `fwup`.
[Our Docker image](https://github.com/NervesJP/docker-nerves/blob/ae92d7aad5463992f40ed84bca5a29bc1cc09cd7/Dockerfile#L24) has created this as the follow.

```
RUN ln -s fwup /usr/bin/fwup.exe
```

However, we can evolve the code to do a smarter way.

**Comment by danifv** [comment]
Is this issue fixed for sure? I just ran into this problem while using WSL2.  
Removing `not` from https://github.com/nerves-project/nerves/blob/5cb48faa0f1d640113b5193c240b0b2132251dd9/lib/nerves/utils/wsl.ex#L30 appears to fix the issue.
