### ISSUE TITLE
vm.args.eex check doesn't work with custom `rel_templates_path` for release

### ISSUE THREAD

**Issue by LostKobrakai** [nerves-project/nerves#574]
### Environment

* Elixir version (`elixir -v`): 1.11.2
* Nerves environment: (`mix nerves.env --info`)
==> nerves
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        /Users/benni/Projects/ikea_umbrella

|nerves_bootstrap| Loadpaths End
* Additional information about your host, target hardware or environment that
  may help

### Current behavior

```
==> nerves

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

** (Mix)   rel/vm.args needs to be moved to rel/vm.args.eex
```

### Expected behavior

It should check `rel_templates_path` and not the hardcoded `rel/vm.args.eex`.

Moving the check into `Nerves.Release.init/1` should resolve this problem.

**Comment by fhunleth** [comment]
@LostKobrakai Could you make a PR and verify that it fixes the issue for you?
