### ISSUE TITLE
Question: Use of Logo

### ISSUE THREAD

**Issue by aj-foster** [nerves-project/nerves#603]
Hello there,

I'm creating educational content that mentions the Nerves project as an example of the Elixir language's extensions into various domains. The license attached to this repo says...

```
This License does not grant permission to use the trade
names, trademarks, service marks, or product names of the Licensor,
except as required for reasonable and customary use in describing the
origin of the Work and reproducing the content of the NOTICE file.
```

Given that, do the maintainers of this project object to use of the Nerves logo when referring to the project in a factual / non-normative way?

Thank you!

**Comment by fhunleth** [comment]
Hi @aj-foster. Thanks for asking about the logo. You and PluralSight may use the logo when referring to the Nerves project.
