### ISSUE TITLE
Add update mechanism to nerves_bootstrap

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-project/nerves#61]
Nerves Bootstrap needs to be able to inform the user that there is an update available for their version. we should create a mix task which installs the latest bootstrap version.

**Comment by ghitchens** [comment]
this closes the mix task question but not the inform, did we decide not to inform, or does it do that now?

**Comment by mobileoverlord** [comment]
Well, I guess that this inevitably solves the task at hand. We would need to implement an API on our site to provide bootstrap update requests.

**Comment by ghitchens** [comment]
I guess the notification part is handled by things like ~> "0.2" in mix.exs of the app using it.  I'm ok closing it.
