### ISSUE TITLE
"Let's Go" link in case studies links to same page

### ISSUE THREAD

**Issue by jaimeiniesta** [nerves-project/nerves#665]
Hi, I couldn't find a repo for the Nerves site so I think this is the best place for this issue.

The "Let's Go" at the bottom of each case study page, like in https://www.nerves-project.org/customer-le-tote.html is linking to the same page. I think that it should link to https://hexdocs.pm/nerves/getting-started.html instead, right?

![Captura de pantalla 2021-10-28 a las 18 35 56](https://user-images.githubusercontent.com/2629/139298450-e32b246b-f6c6-4077-a6fb-45c4555c0834.png)

This happens in:

https://www.nerves-project.org/customer-le-tote.html

https://www.nerves-project.org/customer-hop.html

https://www.nerves-project.org/customer-farmbot.html

**Comment by fhunleth** [comment]
Fixed in https://github.com/nerves-project/nerves-project.github.com/pull/64.
