### ISSUE TITLE
Target keyboard layout

### ISSUE THREAD

**Issue by raymondboswel** [nerves-project/nerves#704]
Hi! 

I'm busy hacking on something at home, and being a dvorak typist I'm being hindered by the qwerty layout when hacking on the device. It's not a major pain point, but is there a way to change the keyboard layout on the target device?

Thank you for this amazing project :)

**Comment by fhunleth** [comment]
Hmmm... I don't know. I'm sure that there's some Linux way to do it, but I've never investigated. If it's a kernel option or something like that, then I can point you towards how to apply it to Nerves.

Perhaps the easiest workaround for now is if you can `ssh` into your target device to use it.

**Comment by raymondboswel** [comment]
Ah yes, I forgot about the ssh route. I think that'll be easiest, thanks!
