### ISSUE TITLE
Google linked project web page routes to 404

### ISSUE THREAD

**Issue by mpichette** [nerves-project/nerves#821]
### Environment

Chrome browser

### Current behavior

Clicking on link (https://nerves-project.org/) in Google should redirect to project web page. A 404 Github page is displayed instead.

![image](https://user-images.githubusercontent.com/2471318/214350518-94be43da-600b-411f-ba27-d4e305cbea62.png)

![image](https://user-images.githubusercontent.com/2471318/214350588-320d3d83-eb4c-4275-8fb7-09675f704317.png)

### Expected behavior

Should be directed to project page.

**Comment by fhunleth** [comment]
Thanks for letting us know. I fixed the issue. Hopefully it works for you now.
