### ISSUE TITLE
Help Mod bus, TCP/IP

### ISSUE THREAD

**Issue by aarondonnay** [nerves-project/nerves#867]
Looking for help integrating mod bus, TCP/IP in raspberry pi on our sensor technology

**Comment by jjcarstens** [comment]
👋 hey @aarondonnay! Can you move this question to the Nerves forum as a question with as much details of your problem/need as possible?

https://elixirforum.com/c/nerves-forum/nerves-questions

This isn't necessarily an issue with Nerves but a request for help and there may be many community members that might have more info there.

If we find issues or code needs for the project based on that question, then we can work on getting those changes in
