### ISSUE TITLE
Formatting in installation instructions are unclear

### ISSUE THREAD

**Issue by dpurrington** [nerves-project/nerves#880]
### Environment

n/a

### Current behavior

[These instructions](https://hexdocs.pm/nerves/installation.html#linux) make it appear as if all the text under "For Arch based systems" applies only to Arch-based systems, when in fact they apply to all Linux systems. The result is Debian system users (and others) will not perform all the necessary installation tasks -- specifically installation of `fwup.`

### Expected behavior

It should be clear which tasks apply to all Linux systems, and which are specific to particular distributions.

**Comment by mnishiguchi** [comment]
Thank you for raising this issue!
