### ISSUE TITLE
Update Dependabot settings and CI auto merge

### ISSUE THREAD

**Issue by jjcarstens** [nerves-project/nerves#918]
Issue to track updating projects depdendabot config and CI to enable automerging

See https://github.com/nerves-project/nerves_ssh/commit/3d60d34cb21e2c71930f37c25a5298d59e199f21 for example. Also ensure the `Allow auto-merge` is enabled in the project settings

If you're working on an item, claim the task below with `(your name)`

## nerves-project

- [x] nerves (https://github.com/nerves-project/nerves/pull/919)
- [x] nerves_pack (https://github.com/nerves-project/nerves_pack/pull/209)
- [x] nerves_motd (@mnishiguchi - https://github.com/nerves-project/nerves_motd/pull/149)
- [x] nerves_examples (https://github.com/nerves-project/nerves_examples/pull/282)
- [x] nerves_uevent (https://github.com/nerves-project/nerves_uevent/pull/46)
- [x] ring_logger (https://github.com/nerves-project/ring_logger/pull/148)
- [x] nerves_ssh (https://github.com/nerves-project/nerves_ssh/commit/3d60d34cb21e2c71930f37c25a5298d59e199f21)
- [x] nerves_runtime (https://github.com/nerves-project/nerves_runtime/pull/311)
- [x] nerves_bootstrap (https://github.com/nerves-project/nerves_bootstrap/pull/296)
- [x] property_table (https://github.com/nerves-project/property_table/pull/56)
- [x] ssh_subsystem_fwup (https://github.com/nerves-project/ssh_subsystem_fwup/pull/82)
- [x] nerves_logging (https://github.com/nerves-project/nerves_logging/pull/48)
- [x] uboot_env (https://github.com/nerves-project/uboot_env/pull/82)
- [x] shoehorn (https://github.com/nerves-project/shoehorn/pull/116)

## nerves-time

- [x] nerves_time_rtc_nxp (https://github.com/nerves-time/nerves_time_rtc_nxp/pull/6)
- [x] nerves_time (https://github.com/nerves-time/nerves_time/pull/143)
- [x] nerves_time_zones (https://github.com/nerves-time/nerves_time_zones/pull/117)
- [x] nerves_time_rtc_abracon (https://github.com/nerves-time/nerves_time_rtc_abracon/pull/18)
- [x] nerves_time_rtc_ds3231 (https://github.com/nerves-time/nerves_time_rtc_ds3231/pull/17)

## nerves-networking
- [x] vintage_net_wizard (@mnishiguchi https://github.com/nerves-networking/vintage_net_wizard/pull/354)
- [x] mdns_lite (https://github.com/nerves-networking/mdns_lite/pull/133)
- [x] vintage_net (https://github.com/nerves-networking/vintage_net/pull/499)
- [x] vintage_net_direct (@mnishiguchi https://github.com/nerves-networking/vintage_net_direct/pull/118)
- [x] vintage_net_wifi (@mnishiguchi https://github.com/nerves-networking/vintage_net_wifi/pull/204)
- [x] vintage_net_qmi (@mnishiguchi https://github.com/nerves-networking/vintage_net_qmi/pull/169)
- [x] vintage_net_mobile (@mnishiguchi https://github.com/nerves-networking/vintage_net_mobile/pull/216)
- [x] vintage_net_bridge (@mnishiguchi https://github.com/nerves-networking/vintage_net_bridge/pull/114)
- [x] vintage_net_ethernet (@mnishiguchi https://github.com/nerves-networking/vintage_net_ethernet/pull/109)
- [x] beam_notify (@mnishiguchi https://github.com/nerves-networking/beam_notify/pull/71)
- [x] qmi (@mnishiguchi https://github.com/nerves-networking/qmi/pull/147)
- [x] vintage_net_wireguard (https://github.com/nerves-networking/vintage_net_wireguard/pull/15)

**Comment by fhunleth** [comment]
Looks complete.
