### ISSUE TITLE
Broken links in hex documentation

### ISSUE THREAD

**Issue by radiospiel** [nerves-project/nerves#930]
The documentation on hexdocs.pm contain broken links for some in-doc pages.

For example, this page https://hexdocs.pm/nerves/getting-started.html#development-environment has these links, both linking to a non-existant URL:

    "Visit the [Targets Page](https://hexdocs.pm/nerves/targets.html) for information on what target name"
    ...
    "For more info, refer to [Connecting to your Nerves Target](https://hexdocs.pm/nerves/core/connecting-to-your-nerves-target.html)."

Since understanding targets is something that a beginner would want to understand this really is unfortunate.

**Comment by fhunleth** [comment]
Thank you for reporting both of these broken links. I fixed both.
