### ISSUE TITLE
Stale link in hello_nerves

### ISSUE THREAD

**Issue by icefoxen** [nerves-project/nerves#969]
Sorry if this isn't quite the right repo for this report.

### Environment

* Elixir version: Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Nerves environment: Default created with nerves_bootstrap-1.12.1.ez 
* Additional information about your host, target hardware or environment that may help: Ubuntu 22.04 with nothing too special about it afaik

### Current behavior

Starting up the tutorial project with `mix nerves.new hello_nerves` prints out:

```
Your Nerves project was created successfully.

You should now pick a target. See https://hexdocs.pm/nerves/targets.html#content
for supported targets. ...
```

This link is stale, it should be `https://hexdocs.pm/nerves/supported-targets.html`.  The generated README.md also has the same incorrect link in it.  I'd offer PR's but I don't have much time free rn.  :C

### Expected behavior

Tutorial text refers to correct URL.

Thanks!

**Comment by fhunleth** [comment]
Thanks for the report! This is an easy fix. I'll do it right now.
