### ISSUE TITLE
Feature: Add firewall support?

### ISSUE THREAD

**Issue by icefoxen** [nerves-project/nerves#970]
### Environment

N/A

### Current behavior

No firewall on target system, `iptables` not even installed.

### Expected behavior

I'm making this because I was just like "oh there has to be SOME way of setting it up easily in my `target.exs` or something", but it appears that `iptables` binaries aren't even installed on the target.  I can sympathize with wanting to keep the base image small and simple, but is there an easy guide or such somewhere on how to build a nerves system with `iptables` included?

**Comment by fhunleth** [comment]
Ideally, there would be a hex package that you could depend on to get firewall configuration tools. In the mean time, adding it via a Buildroot config in a custom Nerves system is the way to go. See https://hexdocs.pm/nerves/customizing-systems.html.
