### ISSUE TITLE
`nerves.system.shell` crashes on macos

### ISSUE THREAD

**Issue by Noarkhh** [nerves-project/nerves#977]
### Environment

* Elixir version: 1.16
* MacOS 14.4, M3, 

### Current behavior

When running `nerves.system.shell` inside `nerves_system_rpi4` I get the following error:
```
|Elixir.Docker| Starting Build... (this may take a while)

** (Mix) The Nerves Docker build_runner encountered an error while building:

-----
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.1KMZvn8mWg/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.1KMZvn8mWg/Listeners: operation not supported.

-----

See /Users/noarkhh/Nerves/nerves_system_rpi4_ex_webrtc/build.log.
```

This has to be some problem with ssh forwarding to docker on macos, since when I removed `ssh_agent()` from [this line](https://github.com/nerves-project/nerves/blob/5eb695365786f30a843e7902c6e087325f896654/lib/nerves/artifact/build_runners/docker.ex#L247) and [this line](https://github.com/nerves-project/nerves/blob/5eb695365786f30a843e7902c6e087325f896654/lib/nerves/artifact/build_runners/docker.ex#L142) (although I doubt the second one matters) things started working again.

I think this might have something to do with this issue https://github.com/docker/for-mac/issues/410

**Comment by fhunleth** [comment]
Hi @Noarkhh - Could you try out #972 and see if it works for you?

**Comment by Noarkhh** [comment]
Hi @fhunleth, seems to work, thanks for the quick response!

**Comment by fhunleth** [comment]
@Noarkhh Thanks for following up on this! Always good to know that things work.
