### ISSUE TITLE
Docker permissions issue

### ISSUE THREAD

**Issue by xmyst** [nerves-project/nerves#997]
### Environment

* Elixir version (`elixir -v`):
  ```
  Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

  Elixir 1.17.2 (compiled with Erlang/OTP 26)
  ```
* Nerves environment (`mix nerves.env --info`):
  ```
  ==> nerves
  ==> xxx_rpi5
  Generated xxx_rpi5 app
  |Elixir.Docker| Starting Build... (this may take a while)

  chown: changing ownership of '/nerves/build': Operation not permitted
  could not compile dependency :xxx_rpi5, "mix compile" failed.
  Errors may have been logged above.
  You can recompile this dependency with "mix deps.compile xxx_rpi5 --force",
  update it with "mix deps.update xxx_rpi5" or clean it with "mix deps.clean xxx_rpi5"
  ==> pnp_connect
  ** (Mix) The Nerves Docker build_runner encountered an error while setting permissions:

  %IO.Stream{device: :standard_io, raw: true, line_or_bytes: :line}
  ```
* Additional information about your host, target hardware or environment that may help:

  I suspect it might be connected to the move away from root, i.e. https://github.com/nerves-project/nerves_system_br/blob/v1.28.1/support/docker/nerves_system_br/Dockerfile#L137 vs. https://github.com/nerves-project/nerves/blob/main/lib/nerves/artifact/build_runners/docker.ex#L279. My understanding is that `chown` needs its `sudo` now.

### Current behaviour

```
% mix deps.compile xxx_rpi5 --force
==> nerves
==> xxx_rpi5
Generated xxx_rpi5 app
|Elixir.Docker| Starting Build... (this may take a while)

chown: changing ownership of '/nerves/build': Operation not permitted
could not compile dependency :xxx_rpi5, "mix compile" failed.
Errors may have been logged above.
You can recompile this dependency with "mix deps.compile xxx_rpi5 --force",
update it with "mix deps.update xxx_rpi5" or clean it with "mix deps.clean xxx_rpi5"
==> pnp_connect
** (Mix) The Nerves Docker build_runner encountered an error while setting permissions:

%IO.Stream{device: :standard_io, raw: true, line_or_bytes: :line}
```

### Expected behaviour

It compiles.

**Comment by fhunleth** [comment]
@xmyst I think if you change your `:nerves` dependency to point to the `fix-docker-build` branch from #996 that it should build.

**Comment by fhunleth** [comment]
The dependency needs to be forced. Try this:

```
{:nerves, github: "nerves-project/nerves", branch: "fix-docker-build", override: true, runtime: false},
```

**Comment by fhunleth** [comment]
This looks good. The `MIX_TARGET` setting is expected. The short story is that Mix targets are just mostly arbitrary words (the word `host` is the only that means something since it's used when the target is unset). They are only mainly used to select among library dependencies. In Nerves, we name them things like `rpi5` when pulling in Raspberry Pi 5 dependencies, but in places like here where there's only one way to build, we just call it `target` for consistency.

Thank you for reporting that the build completed!
